# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_DbsTableSelect.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DbsTableSelect(object):
    def setupUi(self, DbsTableSelect):
        DbsTableSelect.setObjectName("DbsTableSelect")
        DbsTableSelect.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DbsTableSelect.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DbsTableSelect)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(DbsTableSelect)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.tableNamesWidget = QtWidgets.QListWidget(DbsTableSelect)
        self.tableNamesWidget.setDragEnabled(True)
        self.tableNamesWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tableNamesWidget.setObjectName("tableNamesWidget")
        self.verticalLayout_6.addWidget(self.tableNamesWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.refreshButton = QtWidgets.QPushButton(DbsTableSelect)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_2.addWidget(self.refreshButton)
        self.chooseButton = QtWidgets.QPushButton(DbsTableSelect)
        self.chooseButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.chooseButton.setFont(font)
        self.chooseButton.setObjectName("chooseButton")
        self.horizontalLayout_2.addWidget(self.chooseButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(DbsTableSelect)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout_6.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(DbsTableSelect)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.tableView = QtWidgets.QTableView(DbsTableSelect)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(True)
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tableView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(DbsTableSelect)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignBottom)
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DbsTableSelect)
        self.pushButton.clicked.connect(DbsTableSelect.backClicked)
        self.tableNamesWidget.itemClicked['QListWidgetItem*'].connect(DbsTableSelect.tableSelected)
        self.refreshButton.clicked.connect(DbsTableSelect.refreshClicked)
        self.chooseButton.clicked.connect(DbsTableSelect.chooseClicked)
        QtCore.QMetaObject.connectSlotsByName(DbsTableSelect)

    def retranslateUi(self, DbsTableSelect):
        _translate = QtCore.QCoreApplication.translate
        DbsTableSelect.setWindowTitle(_translate("DbsTableSelect", "数据表选择"))
        self.label.setText(_translate("DbsTableSelect", "选择数据表"))
        self.refreshButton.setText(_translate("DbsTableSelect", "刷新"))
        self.chooseButton.setText(_translate("DbsTableSelect", "选择"))
        self.label_2.setText(_translate("DbsTableSelect", "表数据预览"))
        self.pushButton.setText(_translate("DbsTableSelect", "返回"))


