# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_propertyForm.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_propertyForm(object):
    def setupUi(self, propertyForm):
        propertyForm.setObjectName("propertyForm")
        propertyForm.resize(256, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(propertyForm)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(propertyForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(250, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.page_color = QtWidgets.QWidget()
        self.page_color.setGeometry(QtCore.QRect(0, 0, 250, 184))
        self.page_color.setObjectName("page_color")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_color)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_color = QtWidgets.QLineEdit(self.page_color)
        self.lineEdit_color.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_color.sizePolicy().hasHeightForWidth())
        self.lineEdit_color.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_color.setFont(font)
        self.lineEdit_color.setObjectName("lineEdit_color")
        self.gridLayout.addWidget(self.lineEdit_color, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page_color)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page_color)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.toolBox.addItem(self.page_color, "")
        self.page_width = QtWidgets.QWidget()
        self.page_width.setGeometry(QtCore.QRect(0, 0, 250, 184))
        self.page_width.setObjectName("page_width")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_width)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalSlider_thickness = QtWidgets.QSlider(self.page_width)
        self.horizontalSlider_thickness.setMinimum(1)
        self.horizontalSlider_thickness.setMaximum(10)
        self.horizontalSlider_thickness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_thickness.setObjectName("horizontalSlider_thickness")
        self.gridLayout_2.addWidget(self.horizontalSlider_thickness, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_width)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_width)
        self.label_4.setMinimumSize(QtCore.QSize(40, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.toolBox.addItem(self.page_width, "")
        self.page_label = QtWidgets.QWidget()
        self.page_label.setGeometry(QtCore.QRect(0, 0, 250, 184))
        self.page_label.setObjectName("page_label")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_label)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_label_content = QtWidgets.QLineEdit(self.page_label)
        self.lineEdit_label_content.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_label_content.sizePolicy().hasHeightForWidth())
        self.lineEdit_label_content.setSizePolicy(sizePolicy)
        self.lineEdit_label_content.setObjectName("lineEdit_label_content")
        self.gridLayout_3.addWidget(self.lineEdit_label_content, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_label)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_content = QtWidgets.QPushButton(self.page_label)
        self.pushButton_content.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_content.setObjectName("pushButton_content")
        self.gridLayout_3.addWidget(self.pushButton_content, 0, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.toolBox.addItem(self.page_label, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(propertyForm)
        self.toolBox.setCurrentIndex(0)
        self.pushButton.clicked.connect(propertyForm.color_pallet)
        self.pushButton_content.clicked.connect(propertyForm.set_content_enable)
        self.horizontalSlider_thickness.sliderMoved['int'].connect(self.label_4.setNum)
        self.lineEdit_label_content.returnPressed.connect(propertyForm.content_clicked)
        QtCore.QMetaObject.connectSlotsByName(propertyForm)

    def retranslateUi(self, propertyForm):
        _translate = QtCore.QCoreApplication.translate
        propertyForm.setWindowTitle(_translate("propertyForm", "Form"))
        self.label.setText(_translate("propertyForm", "R,G,B"))
        self.pushButton.setText(_translate("propertyForm", "Pallet"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_color), _translate("propertyForm", "Color"))
        self.label_2.setText(_translate("propertyForm", "Line Width"))
        self.label_4.setText(_translate("propertyForm", "1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_width), _translate("propertyForm", "Width"))
        self.label_3.setText(_translate("propertyForm", "Content"))
        self.pushButton_content.setText(_translate("propertyForm", "Modify"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_label), _translate("propertyForm", "Label"))


